---
- name: playbook for checksum
  hosts: localhost 
  ##hosts: all
  become: true
  
  vars_files:
    - files_list.yml
  tasks:
    - name: checking current checksum
      stat:
        path: "{{ item.name }}"
      register: test
      with_items: "{{ files }}"
    - name: checksum match
      debug:
        msg : "{{item.item.name}} -----------------------------------------------checsum  matches"
      when:  item.item.checksum == item.stat.checksum
      with_items: "{{ test.results }}"
    
    - name: checksum second match
      debug:
        msg: "{{item.item.name}} ------------------------------------->checksum DOESNOT match" 
      when:  item.item.checksum != item.stat.checksum
      with_items: "{{ test.results }}"
    
